name: Automatic Approve

permissions: {}

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  automatic_approve:
    runs-on: ubuntu-latest

    if: github.repository == 'qmk/qmk_firmware'

    steps:
    - uses: zvecr/automatic-approve-action@safe_files
      with:
        token: ${{ secrets.QMK_BOT_TOKEN }}
        workflows: "labeler.yml,lint.yml,docs.yml"
        safe_files: "keyboards/,docs/"
