name: Build firmware for keyboards
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - handwired/stream_cheap/Zatarian
          - handwired/stream_cheap/Vancurls_Craigerbomb_Scuhzy
        keymap:
          - via

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        persist-credentials: false
        submodules: true

    - name: Build
      id: build
      run: |
        TARGET="${{ matrix.keyboard }}"

        if [ -n "${{ matrix.keymap }}" ]; then
           TARGET="${TARGET}:${{ matrix.keymap }}"
        fi
        
        sed -i 's/run --rm -it/run --rm/' util/docker_build.sh
        util/docker_build.sh ${TARGET}

        ls

        echo ::set-output name=artifact-name::${TARGET//[:<>|*?\\\/]/_}
        echo "Artifact-name: ${{ steps.build.outputs.artifact-name }}"

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "${{ steps.build.outputs.artifact-name }}"
        path: |
          *.hex
          *.bin
      continue-on-error: true
