name: Master Docs

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'docs/**'

jobs:
  docs_main:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    # protect against those who develop with their fork on master
    if: github.repository == 'qmk/qmk_firmware'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y rsync nodejs npm
        npm install -g lunr lunr-languages
        python3 -m pip install -r requirements.txt

    - name: Build docs
      run: ./util/build_translations.sh master

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: site
        git-config-email: hello@qmk.fm
        target-folder: master
