name: PR Lint Format

on:
  pull_request:
    paths:
    - 'drivers/**'
    - 'lib/arm_atsam/**'
    - 'lib/lib8tion/**'
    - 'lib/python/**'
    - 'platforms/**'
    - 'quantum/**'
    - 'tests/**'
    - 'tmk_core/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    container: qmkfm/base_container

    steps:
    - uses: rlespinasse/github-slug-action@v3.x

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: trilom/file-changes-action@v1.2.4
      id: file_changes
      with:
        output: ' '
        fileOutput: ' '

    - name: Run qmk cformat and qmk pyformat
      shell: 'bash {0}'
      run: |
        qmk cformat -n $(< ~/files.txt)
        cformat_exit=$?
        qmk pyformat -n
        pyformat_exit=$?

        exit $((cformat_exit + pyformat_exit))
