name: Lint Format

on:
  pull_request:
    paths:
    - 'drivers/**'
    - 'lib/arm_atsam/**'
    - 'lib/lib8tion/**'
    - 'lib/python/**'
    - 'platforms/**'
    - 'quantum/**'
    - 'tests/**'
    - 'tmk_core/**'
  push:
    branches:
    - master
    - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    container: qmkfm/base_container

    steps:

    - uses: rlespinasse/github-slug-action@v3.x

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: trilom/file-changes-action@v1.2.4
      with:
        output: ' '
        fileOutput: ' '

    - name: Become QMK Bot
      run: |
        git config user.name 'QMK Bot'
        git config user.email 'hello@qmk.fm'

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y dos2unix

    - name: Format files
      shell: 'bash {0}'
      run: |
        qmk cformat $(< ~/files.txt)
        qmk pyformat
        qmk fileformat

    - name: Fail when formatting required
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        for file in $(git diff --name-only); do
          echo "::error file=${file}::::File Requires Formatting"
        done
        test -n "$(git status  --porcelain)" && exit 1

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      if: ${{ github.event_name == 'push' && github.repository == 'qmk/qmk_firmware'}}
      with:
        delete-branch: true
        branch: bugfix/format_${{ env.GITHUB_REF_SLUG }}
        author: QMK Bot <hello@qmk.fm>
        committer: QMK Bot <hello@qmk.fm>
        commit-message: Format code according to conventions
        title: '[CI] Format code according to conventions'
