name: Gem80 Build

permissions:
  contents: read

on:
  # Trigger the workflow on tag creation/push, when tag starts with "ryo-"
  push:
    tags:
      - 'ryo-*'
  # push:
  #   branches: [gem80]
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: 'Branch to build'
        options: [gem80]

concurrency: ci_build-${{ github.event.inputs.branch || github.ref_name }}

jobs:
  ci_builds:
    name: "CI Build"
    timeout-minutes: 1380
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: ${{ github.event.inputs.branch || github.ref }}
        fetch-depth: 0

    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: Run `./compile.sh`
      run: |
        chmod +x compile.sh
        ./compile.sh

        [ ! -f .failed ] || exit 1

    - name: Upload wired version
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ github.event.inputs.branch || github.ref_name }}-wired
        if-no-files-found: ignore
        path: |
          *wired*.bin

    - name: Upload threemode version
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ github.event.inputs.branch || github.ref_name }}-threemode
        if-no-files-found: ignore
        path: |
          *threemode*.bin

    - name: Create draft release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/ryo-')
      with:
        files: |
          *wired*.bin
          *threemode*.bin
          keyboards/nuphy/gem80/ansi/keymaps/via/*via3.json
        tag_name: ${{ github.ref_name }}
        draft: true
        prerelease: true
        token: ${{ secrets.CUSTOM_TOKEN }}
