name: pcilabs firmware CI

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  build_and_release:
  
    permissions:
      packages: write
      contents: write

    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    
    steps:
    - name: disable safe.directory check
      run: git config --global --add safe.directory '*'
    - name: setup qmk
      uses: actions/checkout@v4
    - name: fucking python dependencies broken
      run: /usr/bin/python3 -m pip install -r /__w/qmk_firmware/qmk_firmware/requirements.txt
    - name: deploy submodules
      run: qmk git-submodule -f
    - name: compile firmware for all keyboards
      continue-on-error: true
      run: qmk mass-compile -j0 -f "manufacturer=PCI Labs" || touch .failed
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{github.base_ref || github.ref_name}}
        if-no-files-found: ignore
        path: |
            *.bin
            *.hex
            *.uf2
            .build/failed.*
            .failed
    - name: fail build if any group failed or no files were built
      run: |
        [ ! -f .failed ] || exit 1
        find . -maxdepth 1 -name "*.hex" -o -name "*.bin" -o -name "*.uf2" | grep -q . || exit 1
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: make release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-${{github.base_ref || github.ref_name}}"
        prerelease: true
        title: "build-${{github.base_ref || github.ref_name}}-${{steps.date.outputs.date}}"
        files: |
            *.bin
            *.hex
            *.uf2
      
